server:
  port: 9070
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/advanced?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: cn.future.client.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
mapper:
    mappers:
        - cn.future.client.support.BaseMapper
    not-empty: false
    identity: MYSQL